#User Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: icr.io/my-namespace/user-service
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
---
#Driver Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: icr.io/my-namespace/driver-service
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
---
#Ride Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ride-service
  template:
    metadata:
      labels:
        app: ride-service
    spec:
      containers:
        - name: ride-service
          image: icr.io/my-namespace/ride-service
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
---
#Payment Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: icr.io/my-namespace/payment-service
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"