apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ride-sharing-ingress
spec:
  rules:
    - host: myapp.example.com
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
          - path: /driver
            pathType: Prefix
            backend:
              service:
                name: driver-service
                port:
                  number: 80
          - path: /ride
            pathType: Prefix
            backend:
              service:
                name: ride-service
                port:
                  number: 80
          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 80