#User Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
#Driver Service
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
---
#Ride Service
apiVersion: v1
kind: Service
metadata:
  name: ride-service
spec:
  selector:
    app: ride-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
---
#Payment Service
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP